apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: envoy-gateway
resources:
  - https://github.com/kubernetes-sigs/gateway-api/releases/download/v1.1.0/standard-install.yaml
  - namespace.yaml
  - helm.yaml
  - envoyproxy.yaml
  - gateway.yaml
  - certificate.yaml
  - secret.yaml
