apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kube-prometheus-stack
spec:
  interval: 1h
  path: ./gitops/core/kube-prometheus-stack
  prune: true
  dependsOn:
    - name: namespaces
    - name: external-secrets
    - name: cert-manager
    - name: longhorn
    - name: external-secrets-sync
  sourceRef:
    kind: GitRepository
    name: flux-system
