apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - monitoring.yaml
  - metrics-server.yaml
  - external-dns.yaml
  - cert-manager.yaml
  - teleport.yaml
  - grafana.yaml
  - longhorn.yaml
  - envoy-gateway.yaml
  - s3-proxy.yaml
  - dex.yaml
  - external-secrets.yaml
  - security-system.yaml

