apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - grafana-secret.yaml
  - dex-secret.yaml
  - longhorn-secret.yaml
  - s3-proxy-secret.yaml
  - envoy-gateway-secret.yaml
  - teleport-rbac-secret.yaml
  - cert-manager-issuer-secret.yaml
  - external-dns-secret.yaml
  - kube-prometheus-stack-secret.yaml
  - fluxcd-addons-secret.yaml
